org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.235
loader_version_range=[1,)
mod_id=goety_log_suppressor
mod_name=Goety Log Suppressor
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.twsfts.goetylogsuppressor
